spring.application.name=TesteProdutos
spring.datasource.url=jdbc:mysql://localhost/produto_api
spring.datasource.username=root
spring.datasource.password=06abril2005
server.error.include-stacktrace=never

spring.jpa.hibernate.ddl-auto=create-drop
